
-- für's Anlegen von Tabellen/Indizes
\set TBSDATANAME tbs_ :DBNAME _data
\set TBSINDEXNAME tbs_ :DBNAME _index


\echo '=> Neue Indizes für DB-Optimierung'
CREATE INDEX IDX02_HRDF_ZUGART_TAB ON HRDF_ZUGART_TAB (fk_eckdatenid) TABLESPACE :TBSINDEXNAME;
CREATE INDEX IDX02_HRDF_FPLANFahrtG_TAB ON HRDF_FPLANFahrtG_TAB (fk_eckdatenid) TABLESPACE :TBSINDEXNAME;
CREATE INDEX IDX02_HRDF_FPLANFahrtLaufweg_TAB ON HRDF_FPLANFahrtLaufweg_TAB (fk_eckdatenid, fk_fplanfahrtid, sequenceno) TABLESPACE :TBSINDEXNAME;
CREATE INDEX IDX03_HRDF_FPLANFahrtVE_TAB ON HRDF_FPLANFahrtVE_TAB (fk_eckdatenid) TABLESPACE :TBSINDEXNAME;
CREATE INDEX IDX02_HRDF_FPLANFahrtL_TAB ON HRDF_FPLANFahrtL_TAB (fk_eckdatenid) TABLESPACE :TBSINDEXNAME;
CREATE INDEX IDX02_HRDF_FPLANFahrtR_TAB ON HRDF_FPLANFahrtR_TAB (fk_eckdatenid) TABLESPACE :TBSINDEXNAME;
CREATE INDEX IDX02_HRDF_FPLANFahrtA_TAB ON HRDF_FPLANFahrtA_TAB (fk_eckdatenid) TABLESPACE :TBSINDEXNAME;
CREATE INDEX IDX02_HRDF_FPLANFahrtI_TAB ON HRDF_FPLANFahrtI_TAB (fk_eckdatenid) TABLESPACE :TBSINDEXNAME;
CREATE INDEX IDX03_HRDF_FPLANFahrt_TAB ON HRDF_FPLANFahrt_TAB (fk_eckdatenid, tripno, operationalno) TABLESPACE :TBSINDEXNAME;

DROP INDEX IDX01_HRDF_ATTRIBUT_TAB
CREATE INDEX IDX01_HRDF_ATTRIBUT_TAB ON HRDF_ATTRIBUT_TAB (fk_eckdatenid, languagecode) TABLESPACE tbs_hrdfdb_index;